[package]
name = "calculator"
version = "0.1.0"
authors = ["Fergal Miller <fergalmiller@hotmail.co.uk>"]
edition = "2018"
bitflags = "1.0.4"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.9"
